# Generated by Django 6.0.6 on 2026-06-22 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='clients',
            new_name='recipients',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='start_date',
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала отправки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
    ]
